version: '3.8'

services:
  frontend:
    image: ghcr.io/lotfi-dotcom/artztterminapp:latest # Neuer Pfad zur GitHub Container Registry
    container_name: terminapp_frontend
    ports:
      - "80:80" # Mappt Port 80 des Hosts auf Port 80 des Containers
    restart: always
